name: ✋ Ask a Question
description: Ask us a question
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask us a question!
  - type: input
    id: product
    attributes:
      label: What product(s) do you have a question about?
      placeholder: e.g., Azure Functions
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      placeholder: e.g., Do you have plans to support X? How do I implement Y using this service?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or other things we should know.
      placeholder: e.g., Links to posts, issues, blog posts etc. where you have had similar discussions
    validations:
      required: false
  - type: dropdown
    id: role
    attributes:
      label: What is your current role?
      multiple: false
      options:
        - Student
        - Professional
        - Educator
  - type: dropdown
    id: tech-topic
    attributes:
      label: What technical topic is this question related to?
      multiple: true
      options:
        - AI/Data Science/Machine Learning
        - Application Development
        - Developer Tools
        - Low Code/Fusion Development
        - Other